version: '3.7'

volumes:
  follow-data: {}


networks:
  demo:
    name: demo
    driver: bridge
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  mongofollow:
    image: 'mongo:4.2.6-bionic'
    container_name: mongofollow
    ports:
      - '27017:27017'
    networks:
      - demo
    volumes:
      - follow-data:/data/db
    restart: on-failure  


  followms:
    image: followimg
    container_name: followms
    depends_on:
      - mongofollow
    environment:
      - PORT=5000
    networks:
      - demo
    ports:
      - 5000:8089
    volumes:
      - follow-data:/data/db:rw

  
